config/routes.rb
Bookers1::Application.routes.draw do

resources :books

root :to => 'books#top'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	validates :title, presence: true

	validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def top

  end

  def index
  	@books = Book.all
  	@book = Book.new
  end

  def show
  	@book = Book.find(params[:id])
  end

  def new
  end

  def create
  	 @books = Book.all
     @book = Book.new(book_params)
  	  if @book.save
        flash[:create] = "Book was successfully created."
  	    redirect_to @book
      else
        render 'index'
      end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
        flash[:create] = "Book was successfully updated."
        redirect_to @book
      else
        render 'edit'
      end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path

  end

  private
  def book_params
  	  params.require(:book).permit(:title, :body)

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<h1>Editing Book</h1>
<%= form_for(@book) do |f| %>
 <%= render 'layouts/error_messages', model: f.object %>

	<h4>Title</h4>
	<%= f.text_field :title %>

	<h4>Body</h4>
	<%= f.text_area :body %>

	<br><%= f.submit 'Update Book'%></br>

<%= link_to "show",book_path %>

<%= link_to "back",books_path %>

<% end %>

app/views/books/index.html.erb
<h1>Books</h1>

<table>
<thead>
<tr>
<th>title</th>
<th>body</th>
<th></th>
</tr>
</thead>

<tbody>
<% @books.each do |book| %>
<tr>
	<td><%= book.title %></td>
	<td><%= book.body %></td>
	<td>
		<%= link_to "show", book_path(book) %>
		<%= link_to "edit", edit_book_path(book) %>
		<%= link_to "destroy", book_path(book), method: :delete, "data-confirm" => "Are you sure?" %>
	</td>
</tr>
<% end %>
</tbody>
</table>

<h1>New book</h1>
<%= form_for(@book) do |f| %>
  <%= render 'layouts/error_messages', model: f.object %>

	<h4>Title</h4>
	<%= f.text_field :title %>

	<h4>Body</h4>
	<%= f.text_area :body %>

	<br><%= f.submit 'Create Book'%></br>

<% end %>

app/views/books/new.html.erb
<h1>New book</h1>
<%= form_for(@book) do |f| %>


	<h4>Title</h4>
	<%= f.text_field :title %>

	<h4>Body</h4>
	<%= f.text_area :body %>

	<%= f.submit 'Create Book'%>

<% end %>

app/views/books/show.html.erb
<% if flash[:create] %>
      <div class="flash">
        <%= flash[:create] %>
      </div>
    <% end %>

<h2>Title</h2>
<p><%= @book.title %></p>

<h2>Body</h2>
<p><%= @book.body %></p>


<%= link_to "edit", edit_book_path %>
<%= link_to "back",books_path %>

app/views/books/top.html.erb
<h1>ようこそBookersへ</h1>
<p>Bookersでは、さまざまな書籍に関するあなたの意見や<br>
印象を共有し交換することができます</p>


<%= link_to "start",books_path %>

app/views/layouts/_error_messages.html.erb
<% if @book.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% @book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>